#!/bin/bash
#
###
# Example service. {start, stop}
#
#
# 2016/06/13    hayate
set -e

APP=example
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
PYTHON=/usr/bin/python2.7
LOG=/var/log/$APP
SRC_PATH=/web/$APP
MAIN=$SRC_PATH/serve.py
PORT=7080
# PORT=8080
PROCESS_NUM=1
PID_PATH=/var/run/$APP
DESC=$APP

test -x $PYTHON || exit 1

# create necessary logs directory

if [ ! -d $LOG ]; then
    mkdir $LOG
fi
if [ ! -d $PID_PATH ]; then
    mkdir $PID_PATH
fi


case "$1" in
    start)
        echo "Starting $DESC service: "
        cd $SRC_PATH
        index=0
        while [ "$index" != "$PROCESS_NUM" ]
        do
            listen_port=$(($PORT+$index))
            echo "\tListen on $listen_port ..."
            $PYTHON $MAIN --port=$listen_port --app=$APP > /dev/null 2>&1 &
            index=$(($index+1))
        done
        echo "$DESC."
        ;;
    stop)
        echo "Stop $DESC service: "
        files=$(ls $PID_PATH | grep ^p_.*)
        echo $files
        for file in $files
        do
            echo "\tStop $file"
            set +e
            kill -s HUP $(cat $PID_PATH/$file)
            set -e
            echo "$file."
        done
        echo "$DESC."
        ;;
    *)
        echo "Usage: $DESC {start|stop}"
        exit 1
        ;;
esac
exit 0

